# Makefile.toml

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.full]
command = "cargo"
args = ["build", "--all-features"]

[tasks.binaries]
command = "cargo"
args = ["build", "--features=bin", "--bins"]
condition = { files_exist = ["${CARGO_MAKE_WORKING_DIRECTORY}/src/main.rs"] }

[tasks.examples]
command = "cargo"
args = ["build", "--examples"]
condition = { files_exist = ["${CARGO_MAKE_WORKING_DIRECTORY}/examples"] }

[tasks.test-unit]
command = "cargo"
condition = { files_exist = ["${CARGO_MAKE_WORKING_DIRECTORY}/src/lib.rs"] }
args = ["test", "--lib"]

[tasks.test-integration]
command = "cargo"
args = ["test", "--test", "*", "--all-features"]
condition = { files_exist = ["${CARGO_MAKE_WORKING_DIRECTORY}/tests"] }

[tasks.test]
clear = true
dependencies = [
	"test-unit",
	"test-integration"
]
